# Generated by Django 4.0.4 on 2022-05-05 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('057ab435-6b28-4c9a-b0b7-3f95a3476f0c'), primary_key=True, serialize=False),
        ),
    ]
