# Generated by Django 4.0.4 on 2022-05-05 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0003_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afea638f-7952-446e-98f5-9f25cb389244'), primary_key=True, serialize=False),
        ),
    ]
