# Generated by Django 4.0.4 on 2022-05-06 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0004_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb99ce3a-072b-4d49-bae0-f24cccdf360e'), primary_key=True, serialize=False),
        ),
    ]
