# Generated by Django 4.0.4 on 2022-05-06 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0005_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f44fd7de-035b-46a7-89fe-d380aa02798e'), primary_key=True, serialize=False),
        ),
    ]
