# Generated by Django 4.0.4 on 2022-05-06 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0006_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d135ba8-a70a-48d9-8851-d135fcc27e0e'), primary_key=True, serialize=False),
        ),
    ]
