# Generated by Django 4.0.4 on 2022-05-06 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0007_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d88b0fb-c352-46ca-8b7e-a8f25b423e72'), primary_key=True, serialize=False),
        ),
    ]
