# Generated by Django 4.0.4 on 2022-05-06 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0008_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a2f2442e-7df7-45ad-8d24-d3f6c9142fd4'), primary_key=True, serialize=False),
        ),
    ]
