# Generated by Django 4.0.4 on 2022-05-09 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0009_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10acd3be-07f2-4ed1-935d-1568886d98df'), primary_key=True, serialize=False),
        ),
    ]
