# Generated by Django 4.0.4 on 2022-05-11 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0010_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ca54832c-df78-4596-a548-04b0a6e1d369'), primary_key=True, serialize=False),
        ),
    ]
