# Generated by Django 4.0.4 on 2022-05-11 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('routine_user', '0011_alter_routineuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b52154e8-e772-48ca-90a5-39d45d383f25'), primary_key=True, serialize=False),
        ),
    ]
