# Generated by Django 4.0.4 on 2022-05-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_initial'),
        ('routine_day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_dat_relate', to='routine.routine'),
        ),
    ]
