# Generated by Django 4.0.4 on 2022-05-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_alter_routine_category'),
        ('routine_day', '0002_alter_routineday_routine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='routine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_day_relate', to='routine.routine'),
        ),
    ]
