# Generated by Django 4.0.4 on 2022-05-03 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('a510b26b-5670-4256-8eb6-b740ad85470b'), primary_key=True, serialize=False),
        ),
    ]
