# Generated by Django 4.0.4 on 2022-05-03 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_routineuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('02df1f08-b180-443a-86a9-53e8d76dea3c'), primary_key=True, serialize=False),
        ),
    ]
