# Generated by Django 4.0.4 on 2022-05-03 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_routineuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('c9e2814e-2ca6-4447-91af-142e14ef475f'), primary_key=True, serialize=False),
        ),
    ]
