# Generated by Django 4.0.4 on 2022-05-04 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_routineuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('c1265959-6ed0-4dd8-86d5-a0c2fbcc2a38'), primary_key=True, serialize=False),
        ),
    ]
