# Generated by Django 4.0.4 on 2022-05-04 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_routineuser_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineuser',
            name='account_id',
            field=models.UUIDField(default=uuid.UUID('686af6e8-9c00-4380-acc4-f5cb67d7b215'), primary_key=True, serialize=False),
        ),
    ]
